### ISSUE TITLE
[Backsearch] Redirect for Land Ownership How doc

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-static#12]
## Description
We need to add another page to the static site 'How do we identify land ownership?'
This will be a pdf on the gdrive, but we want a nice url. This means a redirect from the static site.

Can:
landexplorer.coop/land-ownership-how
Point to:
https://docs.google.com/document/d/e/2PACX-1vS46_tTfm9_26NHHiXKcBYeyIfvMai1ed6O30IMpNXi-Tdi43bYDi9VoP7cZpF0vog3v1BEjveleA5S/pub

(Note this doc can be updated and the link will stay the same. I'll make it prettier!)

## Acceptance Criteria
landexplorer.coop/land-ownership-how points to published GDoc

**Comment by King-Mob** [comment]
[Give this a try](https://staging.landexplorer.coop/land-ownership-how)

**Comment by King-Mob** [comment]
I also just did this on prod to avoid having two different links for the license part

[here](https://landexplorer.coop/land-ownership-how)
