### ISSUE TITLE
Quotes Carousel

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-static#3]
Get our quotes carousel working

**Comment by King-Mob** [comment]
One way to fix the quotes carousel would be to delete that section of the site. This is a very attractive option for me

**Comment by King-Mob** [comment]
@lin-d-hop the problems are:
- I can't get the icons working for "next quote" "prev quote"
- When you load it sometimes shows two quotes on top of each other

Deleting this section would be much quicker than fixing these problems. I don't even really know where to start with the second one

**Comment by lin-d-hop** [comment]
Can you just cherry pick the best quote and use that?

**Comment by lin-d-hop** [comment]
Or maybe format differently with a couple of quotes. IMO the best ones are:

Land explorer is an invaluable tool helping our members to quickly research what land can be used in their community for projects that create community energy resilience.
Jon Hall
Communications Officer, Community Energy England

Land Explorer is a go to tool for Oxfordshire Community Land Trust, when looking at prospective sites.
Charlie Fisher
Executive Director, Oxfordshire Community Land Trust

By putting this information in one place and simplifying access, it makes the process much easier, whilst removing significant barriers for groups wishing to plan their neighborhood.
Tony Burton
Neighbourhood Planning London

Maybe a different formatting with three side by side? @King-Mob

**Comment by King-Mob** [comment]
Yes, can target that

**Comment by lin-d-hop** [comment]
Good enough for now :)
