### ISSUE TITLE
Add Analytics Script

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-static#7]
Put this on all pages of landexplorer.coop

`<script async defer data-website-id="adf09492-8408-4d60-85cd-692a012fb72a" src="https://umami.digitalcommons.coop/umami.js"></script>`

**Comment by King-Mob** [comment]
- [x] LX Static site
- [x] TWINE static site
- [x] LX webapp
- [x] TWINE admin dashboard
- [x] TWINE visitor webapp

**Comment by lin-d-hop** [comment]
:tada:
